[package]
name = "bonding-curve-contract-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.bonding-curve-contract]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.41.0"
path = "../../../../framework/meta"
