[package]
name = "second-contract-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.second-contract]
path = ".."

[dependencies.dharitri-sc]
version = "0.54.5"
path = "../../../../../../framework/base"

[dependencies.dharitri-sc-meta-lib]
version = "0.54.5"
path = "../../../../../../framework/meta-lib"
default-features = false
