[package]
name = "panic-message-features-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.panic-message-features]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
path = "../../../../framework/meta-lib"
default-features = false
