[package]
name = "numbat-wasm"
version = "0.0.17"
edition = "2018"

authors = ["contact@dharitri.org"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/TerraDharitri/drt-rs-sdk"
homepage = "https://dharitri.org/"
documentation = "https://docs.dharitri.org/"
description = "Numbat WebAssembly smart contract API"
keywords = ["numbat", "wasm", "webassembly", "blockchain", "contract"]
categories = ["no-std", "wasm", "cryptography::cryptocurrencies", "development-tools"]

[features]
cb_closure_unmanaged_deser = []

[dependencies]
wee_alloc = "0.4"
hex-literal = "0.3.1"
bitflags = "1.3.2"
# git-version = "0.3.5"

[dependencies.drthashbrown]
version = "=0.0.17"
path = "../drthashbrown"

[dependencies.numbat-wasm-derive]
version = "=0.0.17"
path = "../numbat-wasm-derive"

[dependencies.numbat-codec]
version = "0.0.17"
path = "../numbat-codec"
features = ["derive"]
