[package]
name = "digital-cash"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/digital_cash.rs"

[dependencies.dharitri-sc]
version = "0.54.3"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "0.54.3"
path = "../../../framework/scenario"
