[package]
name = "erc20-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.erc20]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.2.6"
path = "../../../../../framework/meta"
