[package]
name = "rewards-distribution"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/rewards_distribution.rs"

[dependencies.dharitri-sc]
version = "1.17.2"
path = "../../../framework/base"

[dependencies.dharitri-sc-modules]
version = "1.17.2"
path = "../../../contracts/modules"

[dev-dependencies.dharitri-sc-scenario]
version = "1.17.2"
path = "../../../framework/scenario"
