[package]
name = "adder-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.adder]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.9.0"
path = "../../../../framework/meta"
default-features = false
