[package]
name = "big-float-features-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.big-float-features]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
path = "../../../../framework/meta-lib"
default-features = false
