[package]
name = "dcdt-system-sc-mock"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/dcdt_system_sc_mock.rs"

[dependencies.dharitri-sc]
version = "1.2.0"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "1.2.0"
path = "../../../framework/scenario"
