[package]
name = "kitty-auction"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.kitty]
version = "0.0.0"
path = "../common/kitty"

[dependencies.kitty-ownership]
version = "0.0.0"
path = "../kitty-ownership"

[dependencies.dharitri-sc]
version = "1.15.0"
path = "../../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "1.15.0"
path = "../../../../framework/scenario"
