[package]
name = "large-storage-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.large-storage]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.6.4"
path = "../../../../framework/meta"
default-features = false
