[package]
name = "digital-cash-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.digital-cash]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.2.0"
path = "../../../../framework/meta"
