[package]
name = "use-module-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.use-module]
path = ".."

[dependencies.dharitri-sc]
version = "0.46.1"
path = "../../../../framework/base"

[dependencies.dharitri-sc-meta]
version = "0.46.1"
path = "../../../../framework/meta"
default-features = false
