[package]
name = "use-module"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/use_module.rs"

[dependencies.dharitri-sc-modules]
version = "1.0.14"
path = "../../../contracts/modules"

[dependencies.dharitri-sc]
version = "1.0.14"
path = "../../../framework/base"
features = [ "alloc" ]

[dev-dependencies.dharitri-sc-scenario]
version = "1.0.14"
path = "../../../framework/scenario"

[dev-dependencies.dharitri-sc-meta]
version = "1.0.14"
path = "../../../framework/meta"
