[package]
name = "erc1155-user-mock-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.erc1155-user-mock]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.0.14"
path = "../../../../../framework/meta"
