[package]
name = "panic-message-features"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/panic_features.rs"

[dependencies.dharitri-sc]
version = "1.7.2"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "1.7.2"
path = "../../../framework/scenario"
