[package]
name = "multi-contract-features-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.multi-contract-features]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.0.8"
path = "../../../../framework/meta"
