[package]
name = "pair-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.order-book-pair]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.41.3"
path = "../../../../../framework/meta"
