[package]
name = "empty-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.empty]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.0.14"
path = "../../../../framework/meta"
