[package]
name = "basic-features-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.basic-features]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.50.5"
path = "../../../../framework/meta"
default-features = false
