[package]
name = "empty-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.empty]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "0.54.5"
path = "../../../../framework/meta-lib"
default-features = false
