[package]
name = "dharitri-chain-core"
version = "0.13.1"
edition = "2021"

authors = ["contact@dharitri.org"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/TerraDharitri/drt-rs-sdk"
homepage = "https://dharitri.org/"
documentation = "https://docs.dharitri.org/"
description = "DharitrI chain interfaces, constants, and base types"
keywords = ["dharitri", "blockchain", "vm", "tools"]
categories = ["cryptography::cryptocurrencies", "development-tools::debugging"]

[dependencies]
bitflags = "=2.8.0"

[dependencies.dharitri-sc-codec]
version = "=0.21.2"
path = "../../data/codec"
features = ["derive"]
