[package]
name = "forwarder-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.forwarder]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.6.2"
path = "../../../../../framework/meta"
default-features = false
