[package]
name = "single-value-repeat"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/single_value_repeat.rs"

[dependencies.benchmark-common]
path = "../benchmark-common"


[dependencies.dharitri-sc]
version = "1.0.1"
path = "../../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "1.0.1"
path = "../../../../framework/scenario"
