[package]
name = "dcdt-transfer-with-fee"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/dcdt_transfer_with_fee.rs"

[dependencies.dharitri-sc]
version = "1.13.6"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "1.13.6"
path = "../../../framework/scenario"
