[package]
name = "basic-features-interact"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[[bin]]
name = "basic-features-interact"
path = "src/bf_interact.rs"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.6"

[dependencies.basic-features]
path = ".."

[dependencies.dharitri-sc-snippets]
version = "1.11.4"
path = "../../../../framework/snippets"
