[package]
name = "basic-features"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/basic_features_main.rs"

[dependencies.dharitri-sc]
version = "0.0.12"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "0.0.12"
path = "../../../framework/scenario"

[dependencies.dharitri-sc-modules]
version = "0.0.12"
path = "../../../contracts/modules"

[dev-dependencies.dcdt-system-sc-mock]
path = "../dcdt-system-sc-mock"
