[package]
name = "formatted-message-features-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["contact@dharitri.org"]

[dev-dependencies]

[dependencies.formatted-message-features]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "0.54.2"
path = "../../../../framework/meta-lib"
default-features = false
