[package]
name = "rust-testing-framework-tester-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.rust-testing-framework-tester]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.15.0"
path = "../../../../framework/meta-lib"
default-features = false
