[package]
name = "formatted-message-features-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["contact@dharitri.org"]

[dev-dependencies]

[dependencies.formatted-message-features]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.4.6"
path = "../../../../framework/meta"
