[package]
name = "use-module"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/use_module.rs"

[dependencies.dharitri-sc-modules]
version = "0.54.2"
path = "../../../contracts/modules"

[dependencies.dharitri-sc]
version = "0.54.2"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "0.54.2"
path = "../../../framework/scenario"

[dev-dependencies.dharitri-sc-meta-lib]
version = "0.54.2"
path = "../../../framework/meta-lib"
