[package]
name = "dharitri-sc"
version = "1.0.1"
edition = "2021"
rust-version = "1.78"

authors = ["contact@dharitri.org"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/TerraDharitri/drt-rs-sdk"
homepage = "https://dharitri.org/"
documentation = "https://docs.dharitri.org/"
description = "Dharitri smart contract API"
keywords = ["dharitri", "wasm", "webassembly", "blockchain", "contract"]
categories = ["no-std", "wasm", "cryptography::cryptocurrencies", "development-tools"]

[package.metadata.docs.rs]
all-features = true

[features]
num-bigint = ["dharitri-sc-codec/num-bigint"]
alloc = []
managed-buffer-builder-cached = []
dcdt-token-payment-legacy-decode = []

[dependencies]
hex-literal = "=0.4.1"
bitflags = "=2.6.0"
num-traits = { version = "=0.2.19", default-features = false }
unwrap-infallible = "0.1.5"

[dependencies.dharitri-sc-derive]
version = "=1.0.1"
path = "../derive"

[dependencies.dharitri-sc-codec]
version = "=1.0.1"
path = "../../data/codec"
features = ["derive"]

[dependencies.dharitri-chain-core]
version = "=1.0.1"
path = "../../chain/core"
