[package]
name = "dcdt-transfer-with-fee-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.dcdt-transfer-with-fee]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.43.4"
path = "../../../../framework/meta"
