[package]
name = "promises-features"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/promises_main.rs"

[dependencies.vault]
path = "../vault"

[dependencies.dharitri-sc]
version = "1.2.6"
path = "../../../../framework/base"
features = ["promises"]

[dependencies.dharitri-sc-wasm-adapter]
version = "1.2.6"
path = "../../../../framework/wasm-adapter"
optional = true

[dev-dependencies.dharitri-sc-scenario]
version = "1.2.6"
path = "../../../../framework/scenario"
