[package]
name = "abi-tester"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/abi_tester.rs"

[dependencies.dharitri-sc]
version = "0.50.5"
path = "../../../framework/base"
features = ["alloc"]

[dev-dependencies.dharitri-sc-scenario]
version = "0.50.5"
path = "../../../framework/scenario"

[dev-dependencies.dharitri-sc-meta]
version = "0.50.5"
path = "../../../framework/meta"
