[package]
name = "child-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.child]
path = ".."

[dependencies.dharitri-sc]
version = "1.0.1"
path = "../../../../../../framework/base"

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
path = "../../../../../../framework/meta-lib"
default-features = false
