[package]
name = "local-dcdt-and-nft-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.local-dcdt-and-nft]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.0.14"
path = "../../../../../framework/meta"
