[package]
name = "dcdt-system-sc-mock-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.dcdt-system-sc-mock]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.0.8"
path = "../../../../framework/meta"
