[package]
name = "recursive-caller"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/recursive_caller.rs"

[features]
ei-unmanaged = ["dharitri-sc/ei-unmanaged"]

[dependencies.vault]
path = "../vault"

[dependencies.dharitri-sc]
version = "1.0.14"
path = "../../../../framework/base"

[dependencies.dharitri-sc-wasm-adapter]
version = "1.0.14"
path = "../../../../framework/wasm-adapter"
optional = true

[dev-dependencies.dharitri-sc-scenario]
version = "1.0.14"
path = "../../../../framework/scenario"
