[package]
name = "execute-on-dest-dcdt-issue-callback"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"


[dependencies.parent]
path = "parent"

[dependencies.child]
path = "child"

[dependencies.dharitri-sc]
version = "1.0.8"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "1.0.8"
path = "../../../framework/scenario"
