[package]
name = "first-contract-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.first-contract]
path = ".."

[dependencies.dharitri-sc]
version = "1.0.8"
path = "../../../../../../framework/base"

[dependencies.dharitri-sc-meta]
version = "1.0.8"
path = "../../../../../../framework/meta"
