[package]
name = "promises-features"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/promises_main.rs"

[dependencies.dharitri-sc]
version = "1.0.1"
path = "../../../../framework/base"

