[package]
name = "crowdfunding-rewa-abi"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@numbat.com>"]
edition = "2018"
publish = false

[dependencies.crowdfunding-rewa]
path = ".."

[dependencies.numbat-wasm]
version = "0.10.3"
path = "../../../../numbat-wasm"

[dependencies.numbat-wasm-debug]
version = "0.10.3"
path = "../../../../numbat-wasm-debug"
