[package]
name = "recursive-caller-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.recursive-caller]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
path = "../../../../../framework/meta-lib"
default-features = false
