[package]
name = "kitty-ownership-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.kitty-ownership]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.0.14"
path = "../../../../../framework/meta"
