[package]
name = "child-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.child]
path = ".."

[dependencies.dharitri-sc]
version = "0.43.4"
path = "../../../../../../framework/base"

[dependencies.dharitri-sc-meta]
version = "0.43.4"
path = "../../../../../../framework/meta"
