[package]
name = "forwarder-raw-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.forwarder-raw]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.0.14"
path = "../../../../../framework/meta"
