[package]
name = "rust-testing-framework-tester"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.dharitri-sc]
version = "1.17.2"
path = "../../../framework/base"
features = [ "alloc" ]

[dev-dependencies.adder]
path = "../../examples/adder"

[dev-dependencies.basic-features]
path = "../../feature-tests/basic-features"

[dev-dependencies.dharitri-sc-scenario]
version = "1.17.2"
path = "../../../framework/scenario"

[dev-dependencies]
num-bigint = "0.4"
num-traits = "0.2"
hex = "0.4"

[dev-dependencies.forwarder]
path = "../composability/forwarder"

[dev-dependencies.vault]
path = "../composability/vault"
