[package]
name = "rewards-distribution-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["contact@dharitri.org"]

[dev-dependencies]

[dependencies.rewards-distribution]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
path = "../../../../framework/meta-lib"
default-features = false
