[package]
name = "transfer-role-features"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dev-dependencies.vault]
path = "../vault"

[dependencies.dharitri-sc]
version = "0.46.1"
path = "../../../../framework/base"

[dependencies.dharitri-sc-modules]
version = "0.46.1"
path = "../../../../contracts/modules"

[dev-dependencies.dharitri-sc-scenario]
version = "0.46.1"
path = "../../../../framework/scenario"
