[package]
name = "nft-minter-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.nft-minter]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.11.2"
path = "../../../../framework/meta"
default-features = false
