[package]
name = "exchange-features-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.exchange-features]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "0.51.1"
path = "../../../../framework/meta-lib"
default-features = false
