[package]
name = "crypto-bubbles"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/crypto_bubbles.rs"

[dependencies.dharitri-sc]
version = "1.15.10"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "1.15.10"
path = "../../../framework/scenario"
