[package]
name = "proxy-test-second"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/proxy-test-second.rs"

[features]
ei-unmanaged = ["dharitri-sc/ei-unmanaged"]

[dependencies.dharitri-sc]
version = "1.0.8"
path = "../../../../framework/base"
features = ["alloc"]

[dev-dependencies.dharitri-sc-scenario]
version = "1.0.8"
path = "../../../../framework/scenario"
