[package]
name = "send-tx-repeat"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/send_tx_repeat.rs"

[dependencies.dharitri-sc]
version = "1.16.0"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "1.16.0"
path = "../../../framework/scenario"
