[package]
name = "vec-repeat-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.vec-repeat]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.4.6"
path = "../../../../../framework/meta"
