[package]
name = "vault"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/vault.rs"


[dependencies.dharitri-sc]
version = "0.51.1"
path = "../../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "0.51.1"
path = "../../../../framework/scenario"
