[package]
name = "kitty-auction-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.kitty-auction]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.4.6"
path = "../../../../../framework/meta"
