[package]
name = "crypto-bubbles-abi"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@numbat.com>"]
edition = "2018"
publish = false

[dependencies.crypto-bubbles]
path = ".."

[dependencies.numbat-wasm]
version = "0.0.9"
path = "../../../../numbat-wasm"

[dependencies.numbat-wasm-debug]
version = "0.0.9"
path = "../../../../numbat-wasm-debug"
