[package]
name = "dharitri-sc-wrewa-swap"
version = "1.8.3"

authors = ["contact@dharitri.org"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/TerraDharitri/drt-rs-sdk"
homepage = "https://dharitri.org/"
documentation = "https://docs.dharitri.org/"
description = "Dharitri Wrapped REWA Smart Contract"
keywords = ["dharitri", "wasm", "webassembly", "blockchain", "contract"]
categories = ["no-std", "wasm", "cryptography::cryptocurrencies"]
edition = "2021"

[lib]
path = "src/wrewa.rs"

[dependencies.dharitri-sc]
version = "1.8.3"
path = "../../../framework/base"

[dependencies.dharitri-sc-modules]
version = "1.8.3"
path = "../../../contracts/modules"

[dev-dependencies.dharitri-sc-scenario]
version = "1.8.3"
path = "../../../framework/scenario"
