[package]
name = "str-repeat"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/str_repeat.rs"

[dependencies.dharitri-sc]
version = "1.7.2"
path = "../../../framework/base"
features = ["alloc"]

[dev-dependencies.dharitri-sc-scenario]
version = "1.7.2"
path = "../../../framework/scenario"
