[package]
name = "ping-pong-rewa"
version = "0.0.2"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/ping_pong.rs"

[dependencies.dharitri-sc]
version = "1.9.0"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "1.9.0"
path = "../../../framework/scenario"

