[package]
name = "crypto-bubbles-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.crypto-bubbles]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
path = "../../../../framework/meta-lib"
default-features = false
