[package]
name = "crowdfunding-dcdt-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.crowdfunding-dcdt]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.0.14"
path = "../../../../framework/meta"
