[package]
name = "nft-storage-prepay-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dev-dependencies]

[dependencies.nft-storage-prepay]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.43.4"
path = "../../../../framework/meta"
