[package]
name = "forwarder-wasm"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"

[dependencies.forwarder]
path = ".."
features = ["ei-unmanaged"]

[dependencies.dharitri-sc-wasm-adapter]
version = "1.0.14"
path = "../../../../../framework/wasm-adapter"
features = ["ei-unmanaged-node"]

[workspace]
members = ["."]
