[package]
name = "nft-storage-prepay"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/nft_storage_prepay.rs"


[dependencies.dharitri-sc]
version = "1.7.2"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "1.7.2"
path = "../../../framework/scenario"
