[package]
name = "dharitri-sc-price-aggregator-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.dharitri-sc-price-aggregator]
path = ".."

[dependencies.dharitri-sc]
version = "1.4.6"
path = "../../../../framework/base"

[dependencies.dharitri-sc-meta]
version = "1.4.6"
path = "../../../../framework/meta"
