[package]
name = "kitty-genetic-alg-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.kitty-genetic-alg]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
path = "../../../../../framework/meta-lib"
default-features = false
