[package]
name = "benchmark-common"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "1.11.2"
path = "../../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "1.11.2"
path = "../../../../framework/scenario"
