[package]
name = "dharitri-sc-snippets"
version = "0.56.1"
edition = "2021"

authors = ["contact@dharitri.org"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/TerraDharitri/drt-rs-sdk"
homepage = "https://dharitri.org/"
documentation = "https://docs.dharitri.org/"
description = "DharitrI framework for building smart contract interaction snippets"
keywords = ["dharitri", "blockchain", "contract", "snippets"]
categories = ["cryptography::cryptocurrencies"]

[features]
default = ["http", "default-tls"]
http = ["dharitri-sdk-http", "tokio"]
dapp = ["dharitri-sdk-dapp"]
default-tls = ["dharitri-sdk-http/default-tls"]
static-tls = ["dharitri-sdk-http/static-tls"]

[dependencies]
hex = "0.4"
base64 = "0.22"
log = "0.4.17"
env_logger = "0.11"
futures = "0.3"
anyhow = "1.0.44"
serde_json = "1.0"

tokio = { version = "1.24", features = ["full"], optional = true }

[dependencies.dharitri-sc-scenario]
version = "=0.56.1"
path = "../scenario"

[dependencies.dharitri-chain-scenario-format]
version = "0.23.0"
path = "../../sdk/scenario-format"

[dependencies.dharitri-sdk]
version = "=0.8.2"
path = "../../sdk/core"

[dependencies.dharitri-sdk-http]
version = "=0.8.2"
path = "../../sdk/http"
optional = true
default-features = false

[dependencies.dharitri-sdk-dapp]
version = "=0.8.2"
path = "../../sdk/dapp"
optional = true
