[package]
name = "alloc-features"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/alloc_features_main.rs"

[dependencies.dharitri-sc]
version = "1.6.4"
path = "../../../framework/base"
features = ["alloc"]

[dev-dependencies.dharitri-sc-scenario]
version = "1.6.4"
path = "../../../framework/scenario"

[dev-dependencies.dcdt-system-sc-mock]
path = "../dcdt-system-sc-mock"
