[package]
name = "lottery-erc20"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@numbat.com>",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[features]
wasm-output-mode = [ "numbat-wasm-node",]

[dependencies.numbat-wasm]
version = "0.10.3"
path = "../../../numbat-wasm"

[dependencies.numbat-wasm-derive]
version = "0.10.3"
path = "../../../numbat-wasm-derive"

[dependencies.numbat-wasm-node]
version = "0.10.3"
path = "../../../numbat-wasm-node"
optional = true

[dependencies.simple-erc20]
path = "../simple-erc20"

[dev-dependencies.numbat-wasm-debug]
version = "0.10.3"
path = "../../../numbat-wasm-debug"
