[package]
name = "order-book-pair"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "1.0.14"
path = "../../../../framework/base"
features = ["alloc"]
