[package]
name = "transfer-role-features-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.transfer-role-features]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.41.3"
path = "../../../../../framework/meta"
