[package]
name = "multisig-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.multisig]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.4.6"
path = "../../../../framework/meta"
