[package]
name = "empty"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/empty.rs"

[dependencies.dharitri-sc]
version = "0.41.0"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "0.41.0"
path = "../../../framework/scenario"

[dev-dependencies]
num-bigint = "0.4.2"
