[package]
name = "crypto-bubbles-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.crypto-bubbles]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.11.6"
path = "../../../../framework/meta"
default-features = false
