[package]
name = "send-tx-repeat-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.send-tx-repeat]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.4.10"
path = "../../../../framework/meta"
