[package]
name = "factory-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.order-book-factory]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.6.2"
path = "../../../../../framework/meta"
default-features = false
