[package]
name = "token-release-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dev-dependencies]

[dependencies.token-release]
path = ".."

[dependencies.dharitri-sc-meta]
version = "1.2.0"
path = "../../../../framework/meta"

