[package]
name = "forwarder-legacy"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/forwarder_legacy_main.rs"

[dependencies.vault]
path = "../vault"

[dependencies.dharitri-sc]
version = "0.54.5"
path = "../../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "0.54.5"
path = "../../../../framework/scenario"

