[package]
name = "multi-contract-features"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/multi_contract_features.rs"

[dependencies.dharitri-sc]
version = "1.0.8"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "1.0.8"
path = "../../../framework/scenario"
