[package]
name = "proxy-pause"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/proxy_pause.rs"

[dependencies.dharitri-sc]
version = "0.41.3"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "0.41.3"
path = "../../../framework/scenario"

[dev-dependencies.use-module]
path = "../../feature-tests/use-module"
